### ISSUE TITLE
Add to Maven Central?

### ISSUE THREAD

**Issue by cgivre** [nayuki/Bitcoin-Cryptography-Library#10]
Hello there, 
Thanks for this great library!  Would you consider adding to maven central so that it can be easily imported into Java projects?
Thanks!!

**Comment by nayuki** [comment]
Thanks for the suggestion. I don't really want to do that because I'm not satisfied with the quality of my work here. This library is a mishmash of tools, not battle-tested, I don't trust that I won't change the API in the future, etc. I also question how useful it is to a developer who wants to develop a Bitcoin client or application.

**Comment by msgilligan** [comment]
@cgivre @nayuki We have been working to modularize bitcoinj and reduce the usage of external dependencies. Our `master` branch (and forthcoming release 0.18) will provide a `bitcoinj-base` module with minimal dependencies (probably only JSpecify nullability annotations, we're currently working to remove slf4j as a dependency)

Our `bitcoinj-core` module currently depends on Bouncy Castle, but we are also developing [secp256k1-jdk](https://github.com/bitcoinj/secp256k1-jdk) which will abstract the dependency on Bouncy Castle for ECDSA and also allow us to use the native libsecp256k1 for ECDSA and Schnorr.

We are also trying to reduce our dependencies on Bouncy Castle for miscellaneous cryptographic functions and your RIPEMD160 implementation might be helpful. See:

* https://github.com/bitcoinj/bitcoinj/issues/3912
* https://github.com/bitcoinj/bitcoinj/issues/3964

Also of potential interest:

* https://github.com/bitcoinj/bitcoinj/issues/3389
* https://github.com/bitcoinj/bitcoinj/issues/3352
* https://github.com/bitcoinj/secp256k1-jdk/issues/21

Any suggestions or contributions would be greatly appreciated!
