### ISSUE TITLE
Public Key Derivation

### ISSUE THREAD

**Issue by ZemindJan** [nayuki/Bitcoin-Cryptography-Library#11]
Hi, I'm using this library for an Ethereum Project in C++. The Keccak function and ECSDA will be invaluable. While I can see there's a good bit of the math for the Secp256k1 curve, I don't see any explicit function to derive public keys from private keys.

Is there a simple way to derive public keys from private keys using this library?

Thank you,

Jan

**Comment by nayuki** [comment]
You will have to do the work yourself. Multiply the secp256k1 base point by the private key, serialize it to bytes, take the appropriate RIPEMD-160 and SHA-256 hashes, convert it to Base58.
