### ISSUE TITLE
unsure how to impliment

### ISSUE THREAD

**Issue by tecan** [nayuki/Bitcoin-Cryptography-Library#4]
https://github.com/tecan/EcoCoin starting work on a new type of cryptocoin , is there a more in depth guide to  what 		pubPointX  pubPointY   and r and s values are suposed to be ? ( scratches head) also how would i get a message hash from a string or file using these utils ?

**Comment by sleepdefic1t** [comment]
@tecan
You can see one implementation here:
> https://github.com/sleepdefic1t/cpp-crypto/blob/compliant/src/helpers/crypto.h

This stuff is hard to wrap your head around,
but you’ll get there 👍
